apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gotify
  namespace: argocd
spec:
  destination:
    namespace: gotify
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: gotify
    targetRevision: 1.2.10
    helm:
      values: |-
        common:
          persistence:
            volumes:
            - name: data
              size: 2Gi
              storageClassName: nfs-client
              containerMount: /app/data/
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
