apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-storage
  namespace: loki
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values:
           - centre.s6n.jp
