apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.0
    helm:
      values: |-
        controller:
          replicaCount: "2"
          extraArgs:
            enable-ssl-passthrough: true
            default-ssl-certificate: ingress-nginx/default-certificate-tls
        defaultBackend:
          enabled: "true"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
