apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s6n-jp-server-cert
  namespace: s6n-jp
spec:
  secretName: s6n-jp-server-tls
  commonName: s6n-jp.k8s.s6n.jp
  dnsNames:
  - s6n-jp.k8s.s6n.jp
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
