---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: immich
  name: immich-database
spec:
  instances: 1
  storage:
    storageClass: rook-ceph-block
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  namespace: immich
  name: immich-database
spec:
  name: app
  owner: app
  cluster:
    name: immich-database
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present
    - name: cube
      ensure: present
