apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-volume-claim
  namespace: immich
spec:
  resources:
    requests:
      storage: 32Gi
  storageClassName: "nfs-client"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
