apiVersion: v1
kind: Service
metadata:
  name: paseo-hub
  namespace: paseo-hub
  labels:
    app.kubernetes.io/name: paseo-hub
    app.kubernetes.io/component: hub
spec:
  selector:
    app.kubernetes.io/name: paseo-hub
    app.kubernetes.io/component: hub
  ports:
  - name: http
    port: 80
    targetPort: http
