persistence:
  enabled: true
  size: 16Gi

extraSecretMounts:
- name: grafana-oauth
  secretName: grafana-oauth
  mountPath: /etc/secrets/grafana-oauth
  defaultMode: 0440
  readOnly: true

admin:
  existingSecret: grafana-admin

adminUser: siketyan

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: "Loki"
      type: loki
      access: proxy
      url: http://loki-gateway.loki.svc.cluster.local.

grafana.ini:
  auth.generic_oauth:
    enabled: true
    allow_sign_up: false
    use_pkce: true
    use_refresh_token: true
    api_url: https://api-gw.uid2.alpha.ui.com/idp/api/v1/public/oauth/8b881c60-8e3d-4131-ac41-a936254c7c6e/userinfo
    auth_url: https://api-gw.uid2.alpha.ui.com/idp/api/v1/public/oauth/8b881c60-8e3d-4131-ac41-a936254c7c6e/authorize
    token_url: https://api-gw.uid2.alpha.ui.com/idp/api/v1/public/oauth/8b881c60-8e3d-4131-ac41-a936254c7c6e/token
    client_id: $__file{/etc/secrets/grafana-oauth/client_id}
    client_secret: $__file{/etc/secrets/grafana-oauth/client_secret}
