persistence:
  enabled: true
  size: 16Gi

extraSecretMounts:
- name: grafana-google
  secretName: grafana-google
  mountPath: /etc/secrets/grafana-google
  defaultMode: 0440
  readOnly: true

admin:
  existingSecret: grafana-admin

adminUser: siketyan

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: "Loki"
      type: loki
      access: proxy
      url: http://loki-gateway.loki.svc.cluster.local.

grafana.ini:
  server:
    root_url: https://grafana.k8s.s6n.jp/
  auth:
    disable_login_form: true
    oauth_allow_insecure_email_lookup: true
  auth.google:
    enabled: true
    allow_sign_up: false
    client_id: $__file{/etc/secrets/grafana-google/client_id}
    client_secret: $__file{/etc/secrets/grafana-google/client_secret}
    scopes: openid email profile https://www.googleapis.com/auth/cloud-identity.groups.readonly
    auth_url: https://accounts.google.com/o/oauth2/v2/auth
    token_url: https://oauth2.googleapis.com/token
    api_url: https://openidconnect.googleapis.com/v1/userinfo
    allowed_domains: s6n.jp
    hosted_domain: s6n.jp
    use_pkce: true
