apiVersion: v1
kind: PersistentVolume
metadata:
  name: htdocs-volume
  namespace: s6n-jp
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: htdocs-storage-class
  local:
    path: /srv/s6n-jp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - centre.s6n.jp
