apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: lb-s6n-jp
  namespace: s6n-jp
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: s6n-jp.k8s.s6n.jp
  upstreams:
  - name: s6n-jp
    service: s6n-jp-service
    port: 443
  action:
    pass: s6n-jp
  serverSnippets: |
    allow all;
