apiVersion: apps/v1
kind: Deployment
metadata:
  name: s6n-jp
  namespace: s6n-jp
spec:
  selector:
    matchLabels:
      app: s6n-jp
  template:
    metadata:
      labels:
        app: s6n-jp
    spec:
      containers:
      - name: s6n-jp
        image: ghcr.io/siketyan/h123:latest
        command:
          - "/bin/h123"
          - "--cert-chain-pem"
          - "/certs/tls.crt"
          - "--private-key-pem"
          - "/certs/tls.key"
          - "--document-root"
          - "/htdocs"
          - "--bind-to"
          - "0.0.0.0:18443"
        env:
          - name: RUST_LOG
            value: DEBUG
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: https
          containerPort: 18443
          protocol: TCP
        volumeMounts:
        - name: secret-server-cert
          mountPath: /certs
          readOnly: true
        - name: htdocs
          mountPath: /htdocs
          readOnly: true
      volumes:
      - name: secret-server-cert
        secret:
          secretName: s6n-jp-server-tls
      - name: htdocs
        persistentVolumeClaim:
          claimName: htdocs-volume-claim
