apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-repo-server-cert
  namespace: argocd
spec:
  secretName: argocd-repo-server-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    countries:
    - JP
    provinces:
    - Tokyo
    localities:
    - Kita
    organizations:
    - Naoki Ikeguchi
  commonName: argocd.k8s.s6n.jp
  dnsNames:
  - argocd.k8s.s6n.jp
  usages:
  - server auth
  - client auth
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
