apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  addresses:
  - 172.16.8.250-172.16.8.254
  - 240b:10:9080:8200:c0:ffee::/96
  autoAssign: true
