apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    chart: home-assistant
    targetRevision: 0.2.79
    helm:
      values: |-
        persistence:
          enabled: true
          storageClass: nfs-client
        hostNetwork: true
        env:
        - name: TZ
          value: Asia/Tokyo
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
