apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    chart: home-assistant
    targetRevision: 0.2.79
    helm:
      values: |-
        env:
        - name: TZ
          value: Asia/Tokyo
        hostNetwork: true
        ingress:
          enabled: true
          className: nginx
          annoations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
          - host: home-assistant.k8s.s6n.jp
            paths:
              - path: /
                pathType: Prefix
          tls:
          - hosts:
            - home-assistant.k8s.s6n.jp
            secretName: home-assistant-ingress-tls
        configuration:
          enabled: true
        persistence:
          enabled: true
          storageClass: nfs-client
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
