apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
spec:
  destination:
    namespace: atlantis
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/runatlantis/helm-charts.git
    path: charts/atlantis
    targetRevision: atlantis-4.18.0
    helm:
      parameters:
      - name: ingress.enabled
        value: "false"
      values: |-
        vcsSecretName: vcs-credentials
        githubApp:
          id: 266920
        orgAllowlist: "github.com/siketyan/*,github.com/s6n-jp/*"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
