apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "7.2.3"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
