apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-config
  namespace: homebridge
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/homebridge
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values:
           - centre.s6n.jp
