apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlantis-data-volume-0
  namespace: atlantis
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/atlantis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values:
           - centre.s6n.jp
