apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate-connector
  namespace: argocd
spec:
  destination:
    namespace: twingate-connector
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://twingate.github.io/helm-charts
    chart: connector
    targetRevision: 0.1.30
    helm:
      parameters:
      - name: connector.network
        value: s6n
      - name: connector.existingSecret
        value: twingate-api-credentials
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
