apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  destination:
    namespace: tempo
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.17.0
    helm:
      parameters:
      - name: persistence.enabled
        value: "true"
      - name: persistence.storageClassName
        value: nfs-client
      - name: tempoQuery.enabled
        value: "true"
      - name: tempo.tag
        value: 2.5.0
      - name: tempoQuery.tag
        value: 2.5.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: tempo
    jsonPointers:
    - /spec/volumeClaimTemplates/0/apiVersion
    - /spec/volumeClaimTemplates/0/kind
