apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: cert-manager
spec:
  acme:
    email: me@s6n.jp
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-secret
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          hostedZoneID: Z03630992A14GBQBRDARG
          accessKeyIDSecretRef:
            name: aws-route53-credentials
            key: access_key_id
          secretAccessKeySecretRef:
            name: aws-route53-credentials
            key: secret_access_key
