apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  scopes: '[groups, email]'
  policy.csv: |
    g, Admin, role:admin
    g, me@s6n.jp, role:admin
